### ISSUE TITLE
why if i run the code will this error

### ISSUE THREAD

**Issue by xxdoc** [EduardoVB/ColorControls#1]
Public Sub SetCompact(Optional RecentColorsColumns As Long = 0, Optional ColorValuesSectionVisible As Boolean = False, Optional SliderOptionsAvailable As CDSliderOptionsAvailableConstants = cdSliderOptionsNone, Optional nDialogCaptionVisible As Boolean = True, Optional nConfirmationButtonsVisible As Boolean = True, Optional nColorSelectionBoxVisible As Boolean = True, Optional nSliderWide As CDYesNoAutoConstants = **cdYNAuto**, Optional nHideLabels As Boolean = False)
    mDlg.SetCompact RecentColorsColumns, ColorValuesSectionVisible, SliderOptionsAvailable, nDialogCaptionVisible, nConfirmationButtonsVisible, nColorSelectionBoxVisible, nSliderWide, nHideLabels
End Sub

---------------------------------------
Microsoft Visual Basic
---------------------------------------
Compile Error:

Circular correlation between modules
---------------------------------------
OK help
---------------------------------------

**Comment by xxdoc** [comment]
Public Sub SetComplete(Optional SizeBig As Boolean = False, Optional BasicColorsVisible As Boolean = True, Optional nRecentColorsColumns As Long = 2, Optional SliderOptionsAvailable As CDSliderOptionsAvailableConstants = **cdSliderOptionsAll**, Optional PaletteTypeControlVisible As Boolean = True, Optional ColorSystemControlVisible As Boolean = True, Optional EyeDropperVisible As Boolean = True)
    mDlg.SetComplete SizeBig, BasicColorsVisible, nRecentColorsColumns, SliderOptionsAvailable, PaletteTypeControlVisible, ColorSystemControlVisible
End Sub

the same error

**Comment by EduardoVB** [comment]
The issue was that you have another (newer) version of OLEGuids.tlb registered in your machine, so it is not taken by the IDE and you can see it is missing in the References screen.

To avoid the issue please use the compiled OCX instead.

**Comment by EduardoVB** [comment]
Changed the location of OLEGuids.tlb, now it is expected to be under Windows / System (SysWOW64).

The issue should not happen anymore.
