### ISSUE TITLE
i find why i have this error

### ISSUE THREAD

**Issue by xxdoc** [EduardoVB/ColorControls#2]
ColorControlsConstants.CLS contains custom enumeration types that are referenced in user controls. An error will occur. . . And the ide is just a prompt, it doesn't show which line of code is wrong

---------------------------
Microsoft Visual Basic
---------------------------
模块之间循环相关
---------------------------
确定   帮助   
---------------------------

**Comment by EduardoVB** [comment]
The issue was that you have another (newer) version of OLEGuids.tlb registered in your machine, so it is not taken by the IDE and you can see it is missing in the References screen.

To avoid the issue please use the compiled OCX instead.

**Comment by EduardoVB** [comment]
Changed the location of OLEGuids.tlb, now it is expected to be under Windows / System (SysWOW64).

The issue should not happen anymore.
